# Generated by Django 3.1.3 on 2020-11-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now=True)),
                ('info', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='recording',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
