# Generated by Django 3.1.3 on 2020-11-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0002_auto_20201123_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='streamevent',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
