# Generated by Django 3.1.3 on 2020-11-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201103_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='nav_parents',
            field=models.CharField(choices=[('About', 'About'), ('How To', 'How To'), ('none', 'none')], default='none', max_length=20),
        ),
    ]
